// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpFfq0WLJBo6sI68t5gFhlKaTHUTT9QGQ',
    appId: '1:159353112528:web:7d9b3606d3b6ffeeff5bd5',
    messagingSenderId: '159353112528',
    projectId: 'task-manager-2abf7',
    authDomain: 'task-manager-2abf7.firebaseapp.com',
    storageBucket: 'task-manager-2abf7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2equb1y1mbqM55UxR516RnA5-Opo6pns',
    appId: '1:159353112528:android:14582ef42f3c4dc4ff5bd5',
    messagingSenderId: '159353112528',
    projectId: 'task-manager-2abf7',
    storageBucket: 'task-manager-2abf7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAbOpkSUY4YJZh3pIkdtMw69qnV1kdZZk',
    appId: '1:159353112528:ios:9b352f36fa884d14ff5bd5',
    messagingSenderId: '159353112528',
    projectId: 'task-manager-2abf7',
    storageBucket: 'task-manager-2abf7.appspot.com',
    iosBundleId: 'com.example.taskmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAbOpkSUY4YJZh3pIkdtMw69qnV1kdZZk',
    appId: '1:159353112528:ios:de90447519cd6abeff5bd5',
    messagingSenderId: '159353112528',
    projectId: 'task-manager-2abf7',
    storageBucket: 'task-manager-2abf7.appspot.com',
    iosBundleId: 'com.example.taskmanager.RunnerTests',
  );
}
